@extends('layouts.app')

@section('content')
<div class="container-fluid tambah-pembelian-container mt-4">
    <div class="row">
        <!-- Kiri: Cari & Tambah Barang -->
        <div class="col-md-7">
        <a href="{{ route('pembelian') }}" class="btn btn-secondary">
        ← batal
        </a>
            <div class="card shadow-sm">
                <div class="card-header bg-white fw-bold d-flex justify-content-between align-items-center">
                    <span>Pilih Barang</span>
                    <small class="text-muted" id="itemCount">
                        Menampilkan <span id="currentItems">0</span> dari <span id="totalItems">{{ $barang->count() }}</span> barang
                    </small>
                </div>
                <div class="card-body">
                    <div class="mb-3 d-flex gap-3">
                        <input type="text" class="form-control" id="searchInput" placeholder="Cari barang...">
                        <select class="form-select" id="filterKategori">
                            <option value="">Semua Kategori</option>
                            @foreach($kategoris as $kategori)
                                <option value="{{ strtolower($kategori->nama_kategori) }}">{{ $kategori->nama_kategori }}</option>
                            @endforeach
                        </select>
                        <select class="form-select" id="itemsPerPage" style="width: 120px;">
                            <option value="5">5 per halaman</option>
                            <option value="10" selected>10 per halaman</option>
                            <option value="20">20 per halaman</option>
                            <option value="50">50 per halaman</option>
                        </select>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover table-bordered">
                            <thead class="table-light">
                                <tr>
                                    <th>Kode</th>
                                    <th>Nama</th>
                                    <th>Merek</th>
                                    <th>Kategori</th>
                                    <th>Stok</th>
                                    <th>Satuan</th>
                                    <th>Harga</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody id="daftarBarang">
                                @foreach ($barang as $b)
                                    <tr data-id="{{ $b->id_barang }}" 
                                        data-nama="{{ $b->nama_barang }}" 
                                        data-harga="{{ $b->harga_barang }}" 
                                        data-satuan="{{ $b->satuan_barang }}"
                                        data-kategori="{{ strtolower($b->nama_kategori ?? '') }}"
                                        data-merek="{{ $b->merek ?? '-' }}">
                                        <td>{{ $b->kode_barang }}</td>
                                        <td>{{ $b->nama_barang }}</td>
                                        <td>{{ $b->merek ?? '-' }}</td>
                                        <td>{{ $b->nama_kategori ?? '-' }}</td>
                                        <td>{{ $b->jumlah_barang }}</td>
                                        <td>{{ $b->satuan_barang }}</td>
                                        <td>Rp {{ number_format($b->harga_barang, 0, ',', '.') }}</td>
                                        <td>
                                            <button class="btn btn-sm btn-success btn-tambah-barang">Tambah</button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    
                    <!-- Pagination Controls -->
                    <div class="d-flex justify-content-between align-items-center mt-3">
                        <div>
                            <button class="btn btn-outline-secondary btn-sm" id="prevPage" disabled>
                                <i class="fas fa-chevron-left"></i> Sebelumnya
                            </button>
                            <button class="btn btn-outline-secondary btn-sm" id="nextPage">
                                Selanjutnya <i class="fas fa-chevron-right"></i>
                            </button>
                        </div>
                        <div id="paginationInfo" class="text-muted small">
                            Halaman 1 dari 1
                        </div>
                        <div id="paginationNumbers" class="btn-group" role="group">
                            <!-- Page numbers will be generated by JavaScript -->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Kanan: Keranjang Pembelian -->
        <div class="col-md-5">
            <div class="card shadow-sm">
                <div class="card-header bg-white fw-bold">Daftar Pembelian</div>
                <div class="card-body">
                    <table class="table table-sm table-bordered">
                        <thead class="table-light">
                            <tr>
                                <th>Nama</th>
                                <th>Qty</th>
                                <th>Satuan</th>
                                <th>Harga</th>
                                <th>Subtotal</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="keranjangPembelian">
                            <!-- Dinamis via JS -->
                        </tbody>
                    </table>

                    <hr>
                    <div class="d-flex justify-content-between mb-2">
                        <span class="fw-bold">Total</span>
                        <span class="fw-bold" id="totalHarga">Rp 0</span>
                    </div>

                    <div class="d-grid gap-2">
                        <button class="btn btn-danger" id="btnResetPembelian">Reset</button>
                        <button class="btn btn-primary" id="btnSimpanPembelian">Simpan Pembelian</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
@endsection

@vite(['resources/css/tambah_pembelian.css', 'resources/js/tambah_pembelian.js'])